"""add epub_path to novels

Revision ID: 32148d03227e
Revises: d0f538ca459a
Create Date: 2025-11-21 15:58:25.231023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32148d03227e'
down_revision = 'd0f538ca459a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epub_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.drop_column('epub_path')

    # ### end Alembic commands ###
