"""Add alignment_task_id and aligned_chapters to Novel

Revision ID: 93324931e715
Revises: b62aa75200f3
Create Date: 2025-11-16 13:03:32.805470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93324931e715'
down_revision = 'b62aa75200f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aligned_chapters', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('alignment_task_id', sa.String(length=255), nullable=True))

    # Обновляем NULL значения на 0
    op.execute("UPDATE novels SET aligned_chapters = 0 WHERE aligned_chapters IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.drop_column('alignment_task_id')
        batch_op.drop_column('aligned_chapters')

    # ### end Alembic commands ###
