"""Add editing prompts to PromptTemplate

Revision ID: ade198205b78
Revises: 
Create Date: 2025-08-05 21:43:51.575378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ade198205b78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_chapters_novel_number'))
        batch_op.drop_index(batch_op.f('idx_chapters_novel_url'))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prompt_templates', ['prompt_template_id'], ['id'])

    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editing_analysis_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('editing_style_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('editing_dialogue_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('editing_final_prompt', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_column('metadata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('editing_final_prompt')
        batch_op.drop_column('editing_dialogue_prompt')
        batch_op.drop_column('editing_style_prompt')
        batch_op.drop_column('editing_analysis_prompt')

    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
        batch_op.create_index(batch_op.f('idx_chapters_novel_url'), ['novel_id', 'url'], unique=False)
        batch_op.create_index(batch_op.f('idx_chapters_novel_number'), ['novel_id', 'chapter_number'], unique=1)

    # ### end Alembic commands ###
