"""Add default_model_id to bilingual_prompt_templates

Revision ID: b62aa75200f3
Revises: bad130ee3e78
Create Date: 2025-11-15 20:09:10.455363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62aa75200f3'
down_revision = 'bad130ee3e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilingual_prompt_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_model_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ai_models', ['default_model_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilingual_prompt_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('default_model_id')

    # ### end Alembic commands ###
