"""add_bilingual_templates_and_alignments

Revision ID: bad130ee3e78
Revises: 9de22844c958
Create Date: 2025-11-15 19:15:43.716875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad130ee3e78'
down_revision = '9de22844c958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bilingual_prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('alignment_prompt', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('validation_prompt', sa.Text(), nullable=True),
    sa.Column('correction_prompt', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('alignment_mode', sa.String(length=50), nullable=True),
    sa.Column('output_format', sa.String(length=50), nullable=True),
    sa.Column('include_confidence', sa.Boolean(), nullable=True),
    sa.Column('include_text_type', sa.Boolean(), nullable=True),
    sa.Column('include_context', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bilingual_alignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('alignment_data', sa.JSON(), nullable=False),
    sa.Column('alignment_method', sa.String(length=50), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('template_used_id', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('coverage_ru', sa.Float(), nullable=True),
    sa.Column('coverage_zh', sa.Float(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('total_pairs', sa.Integer(), nullable=True),
    sa.Column('misalignment_count', sa.Integer(), nullable=True),
    sa.Column('verified_by_human', sa.Boolean(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['template_used_id'], ['bilingual_prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id')
    )
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bilingual_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bilingual_prompt_templates', ['bilingual_template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.alter_column('translated_title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bilingual_template_id')

    op.drop_table('bilingual_alignments')
    op.drop_table('bilingual_prompt_templates')
    # ### end Alembic commands ###
