"""add epub_generation_task_id to novels

Revision ID: d0f538ca459a
Revises: 93324931e715
Create Date: 2025-11-21 15:51:27.180534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f538ca459a'
down_revision = '93324931e715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epub_generation_task_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.drop_column('epub_generation_task_id')

    # ### end Alembic commands ###
